######################################################################
#
# File name : pcpu_top_tb_simulate.do
# Created on: Mon Dec 13 16:38:20 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.pcpu_top_tb xil_defaultlib.glbl

do {pcpu_top_tb_wave.do}

view wave
view structure
view signals

do {pcpu_top_tb.udo}

run 1000ns
