######################################################################
#
# File name : pcpu_top_tb_wave.do
# Created on: Mon Dec 13 16:38:20 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
